### ISSUE TITLE
Move Analytics script to just above </head>

### ISSUE THREAD

**Issue by junseth** [sunnankar/wuc#3]
THis is an asynchronous .js element. It should be put at the top for improved loading spead as well better capturing of metrics.

**Comment by sunnankar** [comment]
Changed this on en/index.php since that gets most of the traffic.

If we move to Jekyll then the theme will likely handle this so can leave it for now with the other pages.

**Comment by junseth** [comment]
Perfect. Probably not worth making any of the view changes before the transition.

**Comment by sunnankar** [comment]
Need to focus on the higher yield changes for now since it will probably take a while to get the new stuff all up and running. I want to have an entire theme layout done in Jekyll so content can be version controlled via Github. So it will be a lot of work getting the theme done and content ported over.

I also have the weusecoins.org domain so I think it might make since to setup a second Github project and start tinkering on a new theme with pushes to that domain.

What do you think?

**Comment by sunnankar** [comment]
@junseth Got the transition done and everything is much faster. Moving everything to the https://github.com/sunnankar/wuc-new/issues repo.
